# Generated by Django 4.2.3 on 2023-07-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=28)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='travel_plan_images/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registered_admin_id', models.IntegerField()),
                ('registered_plans', models.ManyToManyField(through='ActualBackend.RegisteredPlans', to='ActualBackend.user')),
            ],
        ),
        migrations.AddField(
            model_name='registeredplans',
            name='planID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActualBackend.travelplans'),
        ),
        migrations.AddField(
            model_name='registeredplans',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActualBackend.user'),
        ),
        migrations.AlterUniqueTogether(
            name='registeredplans',
            unique_together={('userID', 'planID')},
        ),
    ]
